name: Your Fork

on:
  pull_request_target:
    types: [opened]

jobs:
  close:
    if: github.repository != 'CursoScripting/learn-terraform-github-actions'
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Optional. Post a issue comment just before closing a pull request.
        comment: "Hi! If you are following the Terraform GitHub Actions tutorial"
